/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartIndexRouteImport } from './routes/start/index'
import { Route as ProductionsIndexRouteImport } from './routes/productions/index'
import { Route as CommunityVoicesIndexRouteImport } from './routes/community-voices/index'
import { Route as StartDemoTanstackQueryRouteImport } from './routes/start/demo/tanstack-query'
import { Route as StartDemoTanchatRouteImport } from './routes/start/demo/tanchat'
import { Route as StartDemoStructuredRouteImport } from './routes/start/demo/structured'
import { Route as StartDemoStoreRouteImport } from './routes/start/demo/store'
import { Route as StartDemoImageRouteImport } from './routes/start/demo/image'
import { Route as StartDemoDrizzleRouteImport } from './routes/start/demo/drizzle'
import { Route as StartDemoDbChatApiRouteImport } from './routes/start/demo/db-chat-api'
import { Route as StartDemoDbChatRouteImport } from './routes/start/demo/db-chat'
import { Route as StartDemoClerkRouteImport } from './routes/start/demo/clerk'
import { Route as StartExampleGuitarsIndexRouteImport } from './routes/start/example.guitars/index'
import { Route as StartExampleGuitarsGuitarIdRouteImport } from './routes/start/example.guitars/$guitarId'
import { Route as StartDemoStartServerFuncsRouteImport } from './routes/start/demo/start.server-funcs'
import { Route as StartDemoStartApiRequestRouteImport } from './routes/start/demo/start.api-request'
import { Route as StartDemoFormSimpleRouteImport } from './routes/start/demo/form.simple'
import { Route as StartDemoFormAddressRouteImport } from './routes/start/demo/form.address'
import { Route as StartDemoApiTtsRouteImport } from './routes/start/demo/api.tts'
import { Route as StartDemoApiTranscriptionRouteImport } from './routes/start/demo/api.transcription'
import { Route as StartDemoApiTqTodosRouteImport } from './routes/start/demo/api.tq-todos'
import { Route as StartDemoApiTanchatRouteImport } from './routes/start/demo/api.tanchat'
import { Route as StartDemoApiStructuredRouteImport } from './routes/start/demo/api.structured'
import { Route as StartDemoApiNamesRouteImport } from './routes/start/demo/api.names'
import { Route as StartDemoApiImageRouteImport } from './routes/start/demo/api.image'
import { Route as StartDemoApiAvailableProvidersRouteImport } from './routes/start/demo/api.available-providers'
import { Route as StartDemoStartSsrIndexRouteImport } from './routes/start/demo/start.ssr.index'
import { Route as StartDemoStartSsrSpaModeRouteImport } from './routes/start/demo/start.ssr.spa-mode'
import { Route as StartDemoStartSsrFullSsrRouteImport } from './routes/start/demo/start.ssr.full-ssr'
import { Route as StartDemoStartSsrDataOnlyRouteImport } from './routes/start/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartIndexRoute = StartIndexRouteImport.update({
  id: '/start/',
  path: '/start/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsIndexRoute = ProductionsIndexRouteImport.update({
  id: '/productions/',
  path: '/productions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityVoicesIndexRoute = CommunityVoicesIndexRouteImport.update({
  id: '/community-voices/',
  path: '/community-voices/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoTanstackQueryRoute = StartDemoTanstackQueryRouteImport.update({
  id: '/start/demo/tanstack-query',
  path: '/start/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoTanchatRoute = StartDemoTanchatRouteImport.update({
  id: '/start/demo/tanchat',
  path: '/start/demo/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoStructuredRoute = StartDemoStructuredRouteImport.update({
  id: '/start/demo/structured',
  path: '/start/demo/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoStoreRoute = StartDemoStoreRouteImport.update({
  id: '/start/demo/store',
  path: '/start/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoImageRoute = StartDemoImageRouteImport.update({
  id: '/start/demo/image',
  path: '/start/demo/image',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoDrizzleRoute = StartDemoDrizzleRouteImport.update({
  id: '/start/demo/drizzle',
  path: '/start/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoDbChatApiRoute = StartDemoDbChatApiRouteImport.update({
  id: '/start/demo/db-chat-api',
  path: '/start/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoDbChatRoute = StartDemoDbChatRouteImport.update({
  id: '/start/demo/db-chat',
  path: '/start/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoClerkRoute = StartDemoClerkRouteImport.update({
  id: '/start/demo/clerk',
  path: '/start/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const StartExampleGuitarsIndexRoute =
  StartExampleGuitarsIndexRouteImport.update({
    id: '/start/example/guitars/',
    path: '/start/example/guitars/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartExampleGuitarsGuitarIdRoute =
  StartExampleGuitarsGuitarIdRouteImport.update({
    id: '/start/example/guitars/$guitarId',
    path: '/start/example/guitars/$guitarId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartDemoStartServerFuncsRoute =
  StartDemoStartServerFuncsRouteImport.update({
    id: '/start/demo/start/server-funcs',
    path: '/start/demo/start/server-funcs',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartDemoStartApiRequestRoute =
  StartDemoStartApiRequestRouteImport.update({
    id: '/start/demo/start/api-request',
    path: '/start/demo/start/api-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartDemoFormSimpleRoute = StartDemoFormSimpleRouteImport.update({
  id: '/start/demo/form/simple',
  path: '/start/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoFormAddressRoute = StartDemoFormAddressRouteImport.update({
  id: '/start/demo/form/address',
  path: '/start/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoApiTtsRoute = StartDemoApiTtsRouteImport.update({
  id: '/start/demo/api/tts',
  path: '/start/demo/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoApiTranscriptionRoute =
  StartDemoApiTranscriptionRouteImport.update({
    id: '/start/demo/api/transcription',
    path: '/start/demo/api/transcription',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartDemoApiTqTodosRoute = StartDemoApiTqTodosRouteImport.update({
  id: '/start/demo/api/tq-todos',
  path: '/start/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoApiTanchatRoute = StartDemoApiTanchatRouteImport.update({
  id: '/start/demo/api/tanchat',
  path: '/start/demo/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoApiStructuredRoute = StartDemoApiStructuredRouteImport.update({
  id: '/start/demo/api/structured',
  path: '/start/demo/api/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoApiNamesRoute = StartDemoApiNamesRouteImport.update({
  id: '/start/demo/api/names',
  path: '/start/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoApiImageRoute = StartDemoApiImageRouteImport.update({
  id: '/start/demo/api/image',
  path: '/start/demo/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoApiAvailableProvidersRoute =
  StartDemoApiAvailableProvidersRouteImport.update({
    id: '/start/demo/api/available-providers',
    path: '/start/demo/api/available-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartDemoStartSsrIndexRoute = StartDemoStartSsrIndexRouteImport.update({
  id: '/start/demo/start/ssr/',
  path: '/start/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoStartSsrSpaModeRoute =
  StartDemoStartSsrSpaModeRouteImport.update({
    id: '/start/demo/start/ssr/spa-mode',
    path: '/start/demo/start/ssr/spa-mode',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartDemoStartSsrFullSsrRoute =
  StartDemoStartSsrFullSsrRouteImport.update({
    id: '/start/demo/start/ssr/full-ssr',
    path: '/start/demo/start/ssr/full-ssr',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartDemoStartSsrDataOnlyRoute =
  StartDemoStartSsrDataOnlyRouteImport.update({
    id: '/start/demo/start/ssr/data-only',
    path: '/start/demo/start/ssr/data-only',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community-voices': typeof CommunityVoicesIndexRoute
  '/productions': typeof ProductionsIndexRoute
  '/start': typeof StartIndexRoute
  '/start/demo/clerk': typeof StartDemoClerkRoute
  '/start/demo/db-chat': typeof StartDemoDbChatRoute
  '/start/demo/db-chat-api': typeof StartDemoDbChatApiRoute
  '/start/demo/drizzle': typeof StartDemoDrizzleRoute
  '/start/demo/image': typeof StartDemoImageRoute
  '/start/demo/store': typeof StartDemoStoreRoute
  '/start/demo/structured': typeof StartDemoStructuredRoute
  '/start/demo/tanchat': typeof StartDemoTanchatRoute
  '/start/demo/tanstack-query': typeof StartDemoTanstackQueryRoute
  '/start/demo/api/available-providers': typeof StartDemoApiAvailableProvidersRoute
  '/start/demo/api/image': typeof StartDemoApiImageRoute
  '/start/demo/api/names': typeof StartDemoApiNamesRoute
  '/start/demo/api/structured': typeof StartDemoApiStructuredRoute
  '/start/demo/api/tanchat': typeof StartDemoApiTanchatRoute
  '/start/demo/api/tq-todos': typeof StartDemoApiTqTodosRoute
  '/start/demo/api/transcription': typeof StartDemoApiTranscriptionRoute
  '/start/demo/api/tts': typeof StartDemoApiTtsRoute
  '/start/demo/form/address': typeof StartDemoFormAddressRoute
  '/start/demo/form/simple': typeof StartDemoFormSimpleRoute
  '/start/demo/start/api-request': typeof StartDemoStartApiRequestRoute
  '/start/demo/start/server-funcs': typeof StartDemoStartServerFuncsRoute
  '/start/example/guitars/$guitarId': typeof StartExampleGuitarsGuitarIdRoute
  '/start/example/guitars': typeof StartExampleGuitarsIndexRoute
  '/start/demo/start/ssr/data-only': typeof StartDemoStartSsrDataOnlyRoute
  '/start/demo/start/ssr/full-ssr': typeof StartDemoStartSsrFullSsrRoute
  '/start/demo/start/ssr/spa-mode': typeof StartDemoStartSsrSpaModeRoute
  '/start/demo/start/ssr': typeof StartDemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community-voices': typeof CommunityVoicesIndexRoute
  '/productions': typeof ProductionsIndexRoute
  '/start': typeof StartIndexRoute
  '/start/demo/clerk': typeof StartDemoClerkRoute
  '/start/demo/db-chat': typeof StartDemoDbChatRoute
  '/start/demo/db-chat-api': typeof StartDemoDbChatApiRoute
  '/start/demo/drizzle': typeof StartDemoDrizzleRoute
  '/start/demo/image': typeof StartDemoImageRoute
  '/start/demo/store': typeof StartDemoStoreRoute
  '/start/demo/structured': typeof StartDemoStructuredRoute
  '/start/demo/tanchat': typeof StartDemoTanchatRoute
  '/start/demo/tanstack-query': typeof StartDemoTanstackQueryRoute
  '/start/demo/api/available-providers': typeof StartDemoApiAvailableProvidersRoute
  '/start/demo/api/image': typeof StartDemoApiImageRoute
  '/start/demo/api/names': typeof StartDemoApiNamesRoute
  '/start/demo/api/structured': typeof StartDemoApiStructuredRoute
  '/start/demo/api/tanchat': typeof StartDemoApiTanchatRoute
  '/start/demo/api/tq-todos': typeof StartDemoApiTqTodosRoute
  '/start/demo/api/transcription': typeof StartDemoApiTranscriptionRoute
  '/start/demo/api/tts': typeof StartDemoApiTtsRoute
  '/start/demo/form/address': typeof StartDemoFormAddressRoute
  '/start/demo/form/simple': typeof StartDemoFormSimpleRoute
  '/start/demo/start/api-request': typeof StartDemoStartApiRequestRoute
  '/start/demo/start/server-funcs': typeof StartDemoStartServerFuncsRoute
  '/start/example/guitars/$guitarId': typeof StartExampleGuitarsGuitarIdRoute
  '/start/example/guitars': typeof StartExampleGuitarsIndexRoute
  '/start/demo/start/ssr/data-only': typeof StartDemoStartSsrDataOnlyRoute
  '/start/demo/start/ssr/full-ssr': typeof StartDemoStartSsrFullSsrRoute
  '/start/demo/start/ssr/spa-mode': typeof StartDemoStartSsrSpaModeRoute
  '/start/demo/start/ssr': typeof StartDemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community-voices/': typeof CommunityVoicesIndexRoute
  '/productions/': typeof ProductionsIndexRoute
  '/start/': typeof StartIndexRoute
  '/start/demo/clerk': typeof StartDemoClerkRoute
  '/start/demo/db-chat': typeof StartDemoDbChatRoute
  '/start/demo/db-chat-api': typeof StartDemoDbChatApiRoute
  '/start/demo/drizzle': typeof StartDemoDrizzleRoute
  '/start/demo/image': typeof StartDemoImageRoute
  '/start/demo/store': typeof StartDemoStoreRoute
  '/start/demo/structured': typeof StartDemoStructuredRoute
  '/start/demo/tanchat': typeof StartDemoTanchatRoute
  '/start/demo/tanstack-query': typeof StartDemoTanstackQueryRoute
  '/start/demo/api/available-providers': typeof StartDemoApiAvailableProvidersRoute
  '/start/demo/api/image': typeof StartDemoApiImageRoute
  '/start/demo/api/names': typeof StartDemoApiNamesRoute
  '/start/demo/api/structured': typeof StartDemoApiStructuredRoute
  '/start/demo/api/tanchat': typeof StartDemoApiTanchatRoute
  '/start/demo/api/tq-todos': typeof StartDemoApiTqTodosRoute
  '/start/demo/api/transcription': typeof StartDemoApiTranscriptionRoute
  '/start/demo/api/tts': typeof StartDemoApiTtsRoute
  '/start/demo/form/address': typeof StartDemoFormAddressRoute
  '/start/demo/form/simple': typeof StartDemoFormSimpleRoute
  '/start/demo/start/api-request': typeof StartDemoStartApiRequestRoute
  '/start/demo/start/server-funcs': typeof StartDemoStartServerFuncsRoute
  '/start/example/guitars/$guitarId': typeof StartExampleGuitarsGuitarIdRoute
  '/start/example/guitars/': typeof StartExampleGuitarsIndexRoute
  '/start/demo/start/ssr/data-only': typeof StartDemoStartSsrDataOnlyRoute
  '/start/demo/start/ssr/full-ssr': typeof StartDemoStartSsrFullSsrRoute
  '/start/demo/start/ssr/spa-mode': typeof StartDemoStartSsrSpaModeRoute
  '/start/demo/start/ssr/': typeof StartDemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community-voices'
    | '/productions'
    | '/start'
    | '/start/demo/clerk'
    | '/start/demo/db-chat'
    | '/start/demo/db-chat-api'
    | '/start/demo/drizzle'
    | '/start/demo/image'
    | '/start/demo/store'
    | '/start/demo/structured'
    | '/start/demo/tanchat'
    | '/start/demo/tanstack-query'
    | '/start/demo/api/available-providers'
    | '/start/demo/api/image'
    | '/start/demo/api/names'
    | '/start/demo/api/structured'
    | '/start/demo/api/tanchat'
    | '/start/demo/api/tq-todos'
    | '/start/demo/api/transcription'
    | '/start/demo/api/tts'
    | '/start/demo/form/address'
    | '/start/demo/form/simple'
    | '/start/demo/start/api-request'
    | '/start/demo/start/server-funcs'
    | '/start/example/guitars/$guitarId'
    | '/start/example/guitars'
    | '/start/demo/start/ssr/data-only'
    | '/start/demo/start/ssr/full-ssr'
    | '/start/demo/start/ssr/spa-mode'
    | '/start/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community-voices'
    | '/productions'
    | '/start'
    | '/start/demo/clerk'
    | '/start/demo/db-chat'
    | '/start/demo/db-chat-api'
    | '/start/demo/drizzle'
    | '/start/demo/image'
    | '/start/demo/store'
    | '/start/demo/structured'
    | '/start/demo/tanchat'
    | '/start/demo/tanstack-query'
    | '/start/demo/api/available-providers'
    | '/start/demo/api/image'
    | '/start/demo/api/names'
    | '/start/demo/api/structured'
    | '/start/demo/api/tanchat'
    | '/start/demo/api/tq-todos'
    | '/start/demo/api/transcription'
    | '/start/demo/api/tts'
    | '/start/demo/form/address'
    | '/start/demo/form/simple'
    | '/start/demo/start/api-request'
    | '/start/demo/start/server-funcs'
    | '/start/example/guitars/$guitarId'
    | '/start/example/guitars'
    | '/start/demo/start/ssr/data-only'
    | '/start/demo/start/ssr/full-ssr'
    | '/start/demo/start/ssr/spa-mode'
    | '/start/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/community-voices/'
    | '/productions/'
    | '/start/'
    | '/start/demo/clerk'
    | '/start/demo/db-chat'
    | '/start/demo/db-chat-api'
    | '/start/demo/drizzle'
    | '/start/demo/image'
    | '/start/demo/store'
    | '/start/demo/structured'
    | '/start/demo/tanchat'
    | '/start/demo/tanstack-query'
    | '/start/demo/api/available-providers'
    | '/start/demo/api/image'
    | '/start/demo/api/names'
    | '/start/demo/api/structured'
    | '/start/demo/api/tanchat'
    | '/start/demo/api/tq-todos'
    | '/start/demo/api/transcription'
    | '/start/demo/api/tts'
    | '/start/demo/form/address'
    | '/start/demo/form/simple'
    | '/start/demo/start/api-request'
    | '/start/demo/start/server-funcs'
    | '/start/example/guitars/$guitarId'
    | '/start/example/guitars/'
    | '/start/demo/start/ssr/data-only'
    | '/start/demo/start/ssr/full-ssr'
    | '/start/demo/start/ssr/spa-mode'
    | '/start/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityVoicesIndexRoute: typeof CommunityVoicesIndexRoute
  ProductionsIndexRoute: typeof ProductionsIndexRoute
  StartIndexRoute: typeof StartIndexRoute
  StartDemoClerkRoute: typeof StartDemoClerkRoute
  StartDemoDbChatRoute: typeof StartDemoDbChatRoute
  StartDemoDbChatApiRoute: typeof StartDemoDbChatApiRoute
  StartDemoDrizzleRoute: typeof StartDemoDrizzleRoute
  StartDemoImageRoute: typeof StartDemoImageRoute
  StartDemoStoreRoute: typeof StartDemoStoreRoute
  StartDemoStructuredRoute: typeof StartDemoStructuredRoute
  StartDemoTanchatRoute: typeof StartDemoTanchatRoute
  StartDemoTanstackQueryRoute: typeof StartDemoTanstackQueryRoute
  StartDemoApiAvailableProvidersRoute: typeof StartDemoApiAvailableProvidersRoute
  StartDemoApiImageRoute: typeof StartDemoApiImageRoute
  StartDemoApiNamesRoute: typeof StartDemoApiNamesRoute
  StartDemoApiStructuredRoute: typeof StartDemoApiStructuredRoute
  StartDemoApiTanchatRoute: typeof StartDemoApiTanchatRoute
  StartDemoApiTqTodosRoute: typeof StartDemoApiTqTodosRoute
  StartDemoApiTranscriptionRoute: typeof StartDemoApiTranscriptionRoute
  StartDemoApiTtsRoute: typeof StartDemoApiTtsRoute
  StartDemoFormAddressRoute: typeof StartDemoFormAddressRoute
  StartDemoFormSimpleRoute: typeof StartDemoFormSimpleRoute
  StartDemoStartApiRequestRoute: typeof StartDemoStartApiRequestRoute
  StartDemoStartServerFuncsRoute: typeof StartDemoStartServerFuncsRoute
  StartExampleGuitarsGuitarIdRoute: typeof StartExampleGuitarsGuitarIdRoute
  StartExampleGuitarsIndexRoute: typeof StartExampleGuitarsIndexRoute
  StartDemoStartSsrDataOnlyRoute: typeof StartDemoStartSsrDataOnlyRoute
  StartDemoStartSsrFullSsrRoute: typeof StartDemoStartSsrFullSsrRoute
  StartDemoStartSsrSpaModeRoute: typeof StartDemoStartSsrSpaModeRoute
  StartDemoStartSsrIndexRoute: typeof StartDemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/': {
      id: '/start/'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions/': {
      id: '/productions/'
      path: '/productions'
      fullPath: '/productions'
      preLoaderRoute: typeof ProductionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-voices/': {
      id: '/community-voices/'
      path: '/community-voices'
      fullPath: '/community-voices'
      preLoaderRoute: typeof CommunityVoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/tanstack-query': {
      id: '/start/demo/tanstack-query'
      path: '/start/demo/tanstack-query'
      fullPath: '/start/demo/tanstack-query'
      preLoaderRoute: typeof StartDemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/tanchat': {
      id: '/start/demo/tanchat'
      path: '/start/demo/tanchat'
      fullPath: '/start/demo/tanchat'
      preLoaderRoute: typeof StartDemoTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/structured': {
      id: '/start/demo/structured'
      path: '/start/demo/structured'
      fullPath: '/start/demo/structured'
      preLoaderRoute: typeof StartDemoStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/store': {
      id: '/start/demo/store'
      path: '/start/demo/store'
      fullPath: '/start/demo/store'
      preLoaderRoute: typeof StartDemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/image': {
      id: '/start/demo/image'
      path: '/start/demo/image'
      fullPath: '/start/demo/image'
      preLoaderRoute: typeof StartDemoImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/drizzle': {
      id: '/start/demo/drizzle'
      path: '/start/demo/drizzle'
      fullPath: '/start/demo/drizzle'
      preLoaderRoute: typeof StartDemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/db-chat-api': {
      id: '/start/demo/db-chat-api'
      path: '/start/demo/db-chat-api'
      fullPath: '/start/demo/db-chat-api'
      preLoaderRoute: typeof StartDemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/db-chat': {
      id: '/start/demo/db-chat'
      path: '/start/demo/db-chat'
      fullPath: '/start/demo/db-chat'
      preLoaderRoute: typeof StartDemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/clerk': {
      id: '/start/demo/clerk'
      path: '/start/demo/clerk'
      fullPath: '/start/demo/clerk'
      preLoaderRoute: typeof StartDemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/example/guitars/': {
      id: '/start/example/guitars/'
      path: '/start/example/guitars'
      fullPath: '/start/example/guitars'
      preLoaderRoute: typeof StartExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/example/guitars/$guitarId': {
      id: '/start/example/guitars/$guitarId'
      path: '/start/example/guitars/$guitarId'
      fullPath: '/start/example/guitars/$guitarId'
      preLoaderRoute: typeof StartExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/start/server-funcs': {
      id: '/start/demo/start/server-funcs'
      path: '/start/demo/start/server-funcs'
      fullPath: '/start/demo/start/server-funcs'
      preLoaderRoute: typeof StartDemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/start/api-request': {
      id: '/start/demo/start/api-request'
      path: '/start/demo/start/api-request'
      fullPath: '/start/demo/start/api-request'
      preLoaderRoute: typeof StartDemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/form/simple': {
      id: '/start/demo/form/simple'
      path: '/start/demo/form/simple'
      fullPath: '/start/demo/form/simple'
      preLoaderRoute: typeof StartDemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/form/address': {
      id: '/start/demo/form/address'
      path: '/start/demo/form/address'
      fullPath: '/start/demo/form/address'
      preLoaderRoute: typeof StartDemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/api/tts': {
      id: '/start/demo/api/tts'
      path: '/start/demo/api/tts'
      fullPath: '/start/demo/api/tts'
      preLoaderRoute: typeof StartDemoApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/api/transcription': {
      id: '/start/demo/api/transcription'
      path: '/start/demo/api/transcription'
      fullPath: '/start/demo/api/transcription'
      preLoaderRoute: typeof StartDemoApiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/api/tq-todos': {
      id: '/start/demo/api/tq-todos'
      path: '/start/demo/api/tq-todos'
      fullPath: '/start/demo/api/tq-todos'
      preLoaderRoute: typeof StartDemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/api/tanchat': {
      id: '/start/demo/api/tanchat'
      path: '/start/demo/api/tanchat'
      fullPath: '/start/demo/api/tanchat'
      preLoaderRoute: typeof StartDemoApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/api/structured': {
      id: '/start/demo/api/structured'
      path: '/start/demo/api/structured'
      fullPath: '/start/demo/api/structured'
      preLoaderRoute: typeof StartDemoApiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/api/names': {
      id: '/start/demo/api/names'
      path: '/start/demo/api/names'
      fullPath: '/start/demo/api/names'
      preLoaderRoute: typeof StartDemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/api/image': {
      id: '/start/demo/api/image'
      path: '/start/demo/api/image'
      fullPath: '/start/demo/api/image'
      preLoaderRoute: typeof StartDemoApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/api/available-providers': {
      id: '/start/demo/api/available-providers'
      path: '/start/demo/api/available-providers'
      fullPath: '/start/demo/api/available-providers'
      preLoaderRoute: typeof StartDemoApiAvailableProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/start/ssr/': {
      id: '/start/demo/start/ssr/'
      path: '/start/demo/start/ssr'
      fullPath: '/start/demo/start/ssr'
      preLoaderRoute: typeof StartDemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/start/ssr/spa-mode': {
      id: '/start/demo/start/ssr/spa-mode'
      path: '/start/demo/start/ssr/spa-mode'
      fullPath: '/start/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof StartDemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/start/ssr/full-ssr': {
      id: '/start/demo/start/ssr/full-ssr'
      path: '/start/demo/start/ssr/full-ssr'
      fullPath: '/start/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof StartDemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/demo/start/ssr/data-only': {
      id: '/start/demo/start/ssr/data-only'
      path: '/start/demo/start/ssr/data-only'
      fullPath: '/start/demo/start/ssr/data-only'
      preLoaderRoute: typeof StartDemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityVoicesIndexRoute: CommunityVoicesIndexRoute,
  ProductionsIndexRoute: ProductionsIndexRoute,
  StartIndexRoute: StartIndexRoute,
  StartDemoClerkRoute: StartDemoClerkRoute,
  StartDemoDbChatRoute: StartDemoDbChatRoute,
  StartDemoDbChatApiRoute: StartDemoDbChatApiRoute,
  StartDemoDrizzleRoute: StartDemoDrizzleRoute,
  StartDemoImageRoute: StartDemoImageRoute,
  StartDemoStoreRoute: StartDemoStoreRoute,
  StartDemoStructuredRoute: StartDemoStructuredRoute,
  StartDemoTanchatRoute: StartDemoTanchatRoute,
  StartDemoTanstackQueryRoute: StartDemoTanstackQueryRoute,
  StartDemoApiAvailableProvidersRoute: StartDemoApiAvailableProvidersRoute,
  StartDemoApiImageRoute: StartDemoApiImageRoute,
  StartDemoApiNamesRoute: StartDemoApiNamesRoute,
  StartDemoApiStructuredRoute: StartDemoApiStructuredRoute,
  StartDemoApiTanchatRoute: StartDemoApiTanchatRoute,
  StartDemoApiTqTodosRoute: StartDemoApiTqTodosRoute,
  StartDemoApiTranscriptionRoute: StartDemoApiTranscriptionRoute,
  StartDemoApiTtsRoute: StartDemoApiTtsRoute,
  StartDemoFormAddressRoute: StartDemoFormAddressRoute,
  StartDemoFormSimpleRoute: StartDemoFormSimpleRoute,
  StartDemoStartApiRequestRoute: StartDemoStartApiRequestRoute,
  StartDemoStartServerFuncsRoute: StartDemoStartServerFuncsRoute,
  StartExampleGuitarsGuitarIdRoute: StartExampleGuitarsGuitarIdRoute,
  StartExampleGuitarsIndexRoute: StartExampleGuitarsIndexRoute,
  StartDemoStartSsrDataOnlyRoute: StartDemoStartSsrDataOnlyRoute,
  StartDemoStartSsrFullSsrRoute: StartDemoStartSsrFullSsrRoute,
  StartDemoStartSsrSpaModeRoute: StartDemoStartSsrSpaModeRoute,
  StartDemoStartSsrIndexRoute: StartDemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
