/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestimonialsIndexRouteImport } from './routes/testimonials/index'
import { Route as ProductionsIndexRouteImport } from './routes/productions/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as CommunityVoicesIndexRouteImport } from './routes/community-voices/index'
import { Route as CoachingIndexRouteImport } from './routes/coaching/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ProductionsLoginIndexRouteImport } from './routes/productions/login/index'
import { Route as ProductionsEditIndexRouteImport } from './routes/productions/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIndexRoute = TestimonialsIndexRouteImport.update({
  id: '/testimonials/',
  path: '/testimonials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsIndexRoute = ProductionsIndexRouteImport.update({
  id: '/productions/',
  path: '/productions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityVoicesIndexRoute = CommunityVoicesIndexRouteImport.update({
  id: '/community-voices/',
  path: '/community-voices/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingIndexRoute = CoachingIndexRouteImport.update({
  id: '/coaching/',
  path: '/coaching/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsLoginIndexRoute = ProductionsLoginIndexRouteImport.update({
  id: '/productions/login/',
  path: '/productions/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsEditIndexRoute = ProductionsEditIndexRouteImport.update({
  id: '/productions/edit/',
  path: '/productions/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/coaching': typeof CoachingIndexRoute
  '/community-voices': typeof CommunityVoicesIndexRoute
  '/contact': typeof ContactIndexRoute
  '/productions': typeof ProductionsIndexRoute
  '/testimonials': typeof TestimonialsIndexRoute
  '/productions/edit': typeof ProductionsEditIndexRoute
  '/productions/login': typeof ProductionsLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/coaching': typeof CoachingIndexRoute
  '/community-voices': typeof CommunityVoicesIndexRoute
  '/contact': typeof ContactIndexRoute
  '/productions': typeof ProductionsIndexRoute
  '/testimonials': typeof TestimonialsIndexRoute
  '/productions/edit': typeof ProductionsEditIndexRoute
  '/productions/login': typeof ProductionsLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/coaching/': typeof CoachingIndexRoute
  '/community-voices/': typeof CommunityVoicesIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/productions/': typeof ProductionsIndexRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/productions/edit/': typeof ProductionsEditIndexRoute
  '/productions/login/': typeof ProductionsLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/uploadthing'
    | '/coaching'
    | '/community-voices'
    | '/contact'
    | '/productions'
    | '/testimonials'
    | '/productions/edit'
    | '/productions/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/uploadthing'
    | '/coaching'
    | '/community-voices'
    | '/contact'
    | '/productions'
    | '/testimonials'
    | '/productions/edit'
    | '/productions/login'
  id:
    | '__root__'
    | '/'
    | '/api/uploadthing'
    | '/coaching/'
    | '/community-voices/'
    | '/contact/'
    | '/productions/'
    | '/testimonials/'
    | '/productions/edit/'
    | '/productions/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  CoachingIndexRoute: typeof CoachingIndexRoute
  CommunityVoicesIndexRoute: typeof CommunityVoicesIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ProductionsIndexRoute: typeof ProductionsIndexRoute
  TestimonialsIndexRoute: typeof TestimonialsIndexRoute
  ProductionsEditIndexRoute: typeof ProductionsEditIndexRoute
  ProductionsLoginIndexRoute: typeof ProductionsLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/': {
      id: '/testimonials/'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions/': {
      id: '/productions/'
      path: '/productions'
      fullPath: '/productions'
      preLoaderRoute: typeof ProductionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-voices/': {
      id: '/community-voices/'
      path: '/community-voices'
      fullPath: '/community-voices'
      preLoaderRoute: typeof CommunityVoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching/': {
      id: '/coaching/'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions/login/': {
      id: '/productions/login/'
      path: '/productions/login'
      fullPath: '/productions/login'
      preLoaderRoute: typeof ProductionsLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions/edit/': {
      id: '/productions/edit/'
      path: '/productions/edit'
      fullPath: '/productions/edit'
      preLoaderRoute: typeof ProductionsEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  CoachingIndexRoute: CoachingIndexRoute,
  CommunityVoicesIndexRoute: CommunityVoicesIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ProductionsIndexRoute: ProductionsIndexRoute,
  TestimonialsIndexRoute: TestimonialsIndexRoute,
  ProductionsEditIndexRoute: ProductionsEditIndexRoute,
  ProductionsLoginIndexRoute: ProductionsLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
